# Generated by Django 2.1.2 on 2019-03-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('fabricante', models.CharField(max_length=20)),
                ('data_fabricacao', models.DateField()),
                ('modelo', models.CharField(max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
