# Generated by Django 2.1.7 on 2019-03-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_auto_20190329_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computador',
            old_name='fabricante',
            new_name='marca',
        ),
    ]
